CHOST="x86_64-pc-linux-gnu"
x86_64_pc_linux_gnu_CFLAGS="-march=native -pipe -O2"
x86_64_pc_linux_gnu_CXXFLAGS="-march=native -pipe -O2"
i686_pc_linux_gnu_CFLAGS="-march=native -pipe -O2"
i686_pc_linux_gnu_CXXFLAGS="-march=native -pipe -O2"
armv6_unknown_linux_gnueabihf_CFLAGS="-O2 -pipe -march=armv6j -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
armv6_unknown_linux_gnueabihf_CXXFLAGS="-O2 -pipe -march=armv6j -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
armv7_unknown_linux_gnueabi_CFLAGS="-Os -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -pipe"
armv7_unknown_linux_gnueabi_CXXFLAGS="-Os -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -pipe"
